language:
  - node_js
node_js:
  - "0.8"
  - "0.10"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq php5
install:
  - curl -sS https://getcomposer.org/installer | php
before_script:
  - php --version
  - php composer.phar composer --version
  - php composer.phar install
  - npm install -g grunt-cli
  - npm install
